version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.149.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - zipkin

  service_b:
    build:
      context: ./service_b
      dockerfile: Dockerfile
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=service_b
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector

  service_a:
    build:
      context: ./service_a
      dockerfile: Dockerfile
    environment:
      - SERVICE_B_URL=http://service_b:8081
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=service_a
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - service_b
      - otel-collector
